[IV-24-25] Objetivo 2
pablotl0/EnviroTrack pull request #10
Opened 2024-11-13 11:11 UTC by lmchaves

Sobre la estructura del repositorio

* [ ] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [ ] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?

Sobre el planteamiento

* [ ] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [ ] ¿Los issues representan un problema, y no una tarea?

Sobre el análisis del problema

* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

Sobre el código

* [ ] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [ ] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están relacionados con a una HU?
* [ ] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [ ] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2024-11-13 11:22 UTC, lmchaves commented
@pablotl0  ya puedes revisarlo

2024-11-13 19:18 UTC, pablotl0 commented
@lmchaves para modelar el problema faltaría crear constructores para los distintas estructuras y validaciones acordes al dominio del problema

2024-11-13 21:26 UTC, lmchaves commented
he realizado el constructor para la fuenteDatos, para el archivo de calidad_aire.go, creo un constructor de cada estructura nueva creada?

2024-11-14 09:32 UTC, lmchaves commented
@pablotl0 he introducido los contructores, mira a ver si son correctos y si os criterios de validación también lo son.

2024-11-15 09:53 UTC, pablotl0 commented
@lmchaves Con los cambios ya opino que esta bien modelado el problema. Le doy mi aprobado.

2024-11-15 12:46 UTC, pablotl0 commented
@lmchaves falta importar errors para que pueda compilar el proyecto.

2024-11-15 15:04 UTC, lmchaves commented
ya está añadido

2024-11-17 16:59 UTC, pablotl0 approved these changes

2024-11-18 08:39 UTC, lmchaves commented
@JJ puedes revisarlo

2024-11-18 08:43 UTC, JJ commented
@pablotl0 antes de aprobarlo tienes que comprobar los puntos que aparecen en [la lista de seguimiento](http://jj.github.io/IV/documentos/proyecto/2.Modelo)
Os recuerdo que aprobar los PRs sin mirarlos demasiado no ayuda ni a la persona que hace el PR ni a ti, simplemente me carga con más trabajo e indica que realmente no tenéis conocimiento de qué es lo que estáis pidiendo en este milestone.

2024-11-18 08:59 UTC, lmchaves commented
@pablotl0 pon cuando puedas la lista de comprobación, en el mensaje de aprobación

2024-11-18 11:56 UTC, pablotl0 approved these changes
Lista de comprobación para el propietario/a del repositorio

* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-11-18 12:21 UTC, lmchaves commented
@JJ ya está listo para revisar

2024-11-18 18:07 UTC, JJ requested changes
Por favor, haced entre vosotros una ronda de revisión. Os recuerdo que si aprobáis todo lo que se envíe sin ningún tipo de solicitud de modificación, al final es más trabajo para todo el mundo: para el que tiene que revisar, para el que tiene que modificar, pero también para mi.

2024-11-19 11:21 UTC, lmchaves commented
He realizado las modificaciones mencionadas en la anterior revision (sin modificar el archivo de fuentes para poder aclarar si este es servible). @JJ

2024-11-19 12:36 UTC, JJ commented
> @lmchaves para modelar el problema faltaría crear constructores para los distintas estructuras y validaciones acordes al dominio del problema

Pablo, los comentarios tienes que hacerlo en la línea en la que esté el problema. Si no sabes hacerlo, pregunta. Las revisiones a un PR son siempre puntuales y no extensivas.

2024-11-19 12:37 UTC, JJ commented
> Voy a realizar todas las modificaciones mencionadas, como no tener todo el código en un mismo archivo, hacer un control de la hora. Pero por ejemplo, la estructura Ubicación y Datos irregular, como tal no vienen explacadas en la historia de usuario, pero en esta, viene un enlace con el formato de datos necesario para la calidad de aire, y en este archivo se descirben tanto la Ubicación como las 3 maneras de muestreo de los datos, por eso las definí. @JJ

El programa siempre tiene que resolver un problema del usuario, no el de un formato de datos.

2024-11-19 12:39 UTC, JJ requested changes
Aparte de lo dicho, @pablotl0 debería revisarlo de nuevo antes de pedir otra revisión.

2024-11-19 12:39 UTC, JJ commented on internal/calidad_aire.go
> +package internal
... y tienes que resolver todos los comentarios.

2024-11-19 12:39 UTC, JJ commented on internal/datos_muestreo.go
> +	fechaMinima = time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC) // Desde el año 2000
¿De dónde vas a obtener la fecha? ¿Qué vas a hacer con la fecha?
El modelo debe ser un modelo *del problema*.

2024-11-19 18:13 UTC, pablotl0 reviewed
@lmchaves

2024-11-19 22:08 UTC, pablotl0 reviewed
@lmchaves me gustaría aclarar los siguientes conceptos

2024-11-19 22:08 UTC, pablotl0 commented on internal/calidad_aire.go
> +	MetodoEvaluacion   string
¿A que se refiere MetodoEvaluacion?

2024-11-22 12:04 UTC, pablotl0 commented
@lmchaves hay alguno comentarios sin responder sobre distintos ficheros del código

2024-11-22 12:25 UTC, lmchaves commented
@pablotl0 Respondí a los comentarios de la revisión, dime que comentarios te salen sin responder, que no los veo

2024-11-22 12:29 UTC, pablotl0 commented
> @pablotl0 Respondí a los comentarios de la revisión, dime que comentarios te salen sin responder, que no los veo

Estos son: https://github.com/pablotl0/EnviroTrack/pull/10#pullrequestreview-2446747427 y https://github.com/pablotl0/EnviroTrack/pull/10#pullrequestreview-2446200490

2024-11-22 12:54 UTC, lmchaves commented
@pablotl0 vale perdon los escribi, pero no le di a enviar como tal en el review

2024-11-22 13:21 UTC, pablotl0 commented on internal/contaminante.go
> +	Cumplimiento  bool
Creo que este valor no es necesario ya que no se especifíca cuales son los límites, para ser un producto mínimo lo veo prescindible

2024-11-22 14:05 UTC, lmchaves commented
Ya han sido eliminados @pablotl0, ya esta listo para revisar de nuevo

2024-11-22 18:39 UTC, pablotl0 reviewed
@lmchaves tras este último cambio ya veo el modelo adecuado y acorde a las necesidades del investigador. Por lo que tras este cambio te apruebo las modificaciones

2024-11-22 18:39 UTC, pablotl0 commented on internal/calidad_aire.go
> +	Fuente             FuenteDatos
En el contexto del usuario no es una preocupación imprescindible y actual asociar los datos con la fuente, aunque pueda ser útil el cliente no hace referencia a esto. Por lo que para que el producto sea mínimo y de acorde a los deseos del cliente no es necesario.

2024-11-23 17:33 UTC, lmchaves commented on internal/calidad_aire.go
> +	Fuente             FuenteDatos
Ya ha sido eliminado

2024-11-23 17:35 UTC, lmchaves commented
@JJ ya está listo para revisión

2024-11-23 18:33 UTC, lmchaves commented
@JJ ya esta listo para revisión.

2024-11-24 08:33 UTC, pablotl0 approved these changes

2024-11-25 07:41 UTC, JJ commented
Por lo pronto, no te refieres a los issues en los primeros 50 caracteres de los mensajes de commit. Eso implica trabajo adicional para saber con qué issue estás trabajando.

2024-11-25 07:43 UTC, JJ requested changes
Hazlo tanto para el comentario indicado como para el resto. @pablotl0 no puedes aprobar un PR sin que se hayan resuelto correctamente todos los comentarios.

2024-11-25 07:43 UTC, JJ commented on internal/calidad_aire.go
> +package internal
... y resolver los comentarios no es cerrarlos. Tienes que o bien modificar el código al que se refieran o indicar dónde se han cerrado. No dejes el trabajo de averiguar como se ha resuelto a la persona que revisa.

2024-11-25 09:41 UTC, lmchaves commented on internal/calidad_aire.go
> +package internal
Para resolverlo creé los siguientes archivos: datos_muestreo 9080b2b, contaminante.go b5974c1 y ubicación.go df8d664.
Finalmente modifiqué calidad_aire.go 33a863c, para que no estuviera en un mismo fichero. (esos archivos no son las ultimas versiones son de caudno relicé los cambios para este comentario)

2024-11-25 09:44 UTC, lmchaves commented on internal/calidad_aire.go
> +	MetodoEvaluacion   string
Aqui se ha eliminado [c81b9cd](https://github.com/pablotl0/EnviroTrack/pull/10/commits/c81b9cdd02b944d5cb9899832fddc1a34b06b945)

2024-11-25 09:44 UTC, lmchaves commented on internal/contaminante.go
> +	Cumplimiento  bool
Aqui se ha eliminado [c81b9cd](https://github.com/pablotl0/EnviroTrack/pull/10/commits/c81b9cdd02b944d5cb9899832fddc1a34b06b945)

2024-11-25 09:46 UTC, lmchaves commented
En prinicipio ahora los commits estan refereciando a los issues correctamente y los comentarios correctamente resueltos. @pablotl0 ya puedes revisarlo de nuevo

2024-11-25 10:03 UTC, JJ requested changes
@pablotl0 vas a tener que trabajar con el código que @lmchaves haga en el objetivo 4. ¿Crees que si es inválido te va a dar tiempo para la convocatoria ordinaria o siquiera para la extraordinaria?
Por favor, haz un pequeño esfuerzo de ver cómo vas a usarlo, o lo tendrás que hacer el 28 de diciembre o el 24 de enero, cuando igual no sea tan conveniente o tengas otro tipo de presión.

2024-11-25 10:03 UTC, JJ commented on internal/calidad_aire.go
> +	FrecuenciaMuestreo string
Es una pregunta, y por tanto no hay por qué poner en qué commit se ha resuelto. Pero la pregunta *la ha hecho @pablotl0 * Quien tiene que indicar si se resuelve o no es él.
O por otro lado podría darse cuenta de que una solución que tiene la frecuencia de muestreo como string, y tiene tres arrays, solo uno de los cuales sirve, pero que de todas formas se comprueba si alguno de los tres está vacío para darlo como inválido, es posiblemente una solución que necesite considerar otro tipo de factores u otras posibles soluciones. Sobre todo teniendo en cuenta que no está claro qué es lo que soluciona.

2024-11-25 15:24 UTC, lmchaves commented
@pablotl0 está listo para revisión

2024-11-25 15:24 UTC, lmchaves commented on internal/datos_muestreo.go
> +type DatosHorario struct {
Se ha modficado para poder solucionar el problema planteado y trabajar con datos de manera uniforme [d5d4fe3](https://github.com/pablotl0/EnviroTrack/pull/10/commits/d5d4fe33ac6ddde7634b79d1f9a4a314e3626e7b)

2024-11-25 15:25 UTC, lmchaves commented on internal/calidad_aire.go
> +	if len(datosHorario) == 0 && len(datosDiario) == 0 && len(datosIrregular) == 0 {
Ha sido modifcado aqui:  [d5d4fe3](https://github.com/pablotl0/EnviroTrack/pull/10/commits/d5d4fe33ac6ddde7634b79d1f9a4a314e3626e7b)

2024-11-26 09:13 UTC, pablotl0 reviewed
@lmchaves ya está la correción

2024-11-26 09:13 UTC, pablotl0 commented on internal/datos_muestreo.go
> +	FechaFinal    time.Time               // Fecha de fin de muestreo
Si se añade fecha final da lugar a muchas complicaciones (se pueden medir valores entre el dia 13/1 y el 7/6) para hacer un modelo mínimo pienso que se debería usar una única fecha para representar un valor diario de los contaminantes.

2024-11-26 10:07 UTC, lmchaves commented on internal/datos_muestreo.go
> +	FechaFinal    time.Time               // Fecha de fin de muestreo
Ya esta aquí cambiado [752c302](https://github.com/pablotl0/EnviroTrack/pull/10/commits/752c3028f1b28b7020073b53e910b9f49ecfbe1b)

2024-11-26 11:41 UTC, pablotl0 commented
@lmchaves La corrección me parece adecuada, le doy mi visto bueno.

2024-11-26 12:14 UTC, pablotl0 reviewed
@lmchaves Una vez hecho le doy visto bueno.

2024-11-26 12:14 UTC, pablotl0 commented on internal/datos_muestreo.go
> +func NewMuestraCalidadAire(fechaInicial time.Time, contaminantes []Contaminante) (MuestraCalidadAire, error) {
Si solo se van a usar datos diarios hay que asegurarse que solo se usa el día, mes y año. Hay que establecer hora a 00:00:00

2024-11-26 12:43 UTC, lmchaves commented on internal/datos_muestreo.go
> +func NewMuestraCalidadAire(fechaInicial time.Time, contaminantes []Contaminante) (MuestraCalidadAire, error) {
Se ha arreglado aqui:[2111932](https://github.com/pablotl0/EnviroTrack/pull/10/commits/2111932d2c397c6047d7992780dfb1292bb24c75)

2024-11-26 12:44 UTC, lmchaves commented
Ya está listo para revisión @JJ

2024-11-26 13:43 UTC, JJ commented on internal/datos_muestreo.go
> +func NewMuestraCalidadAire(fechaInicial time.Time, contaminantes []Contaminante) (MuestraCalidadAire, error) {
Si quieres aprobarlo, tienes que darle a aprobar, no a "comment"

2024-11-28 09:31 UTC, JJ requested changes
Por favor, dale una vuelta. Mira también los errores frecuentes por si hubiera surgido alguno mientras.

2024-11-28 09:31 UTC, JJ commented on internal/datos_muestreo.go
> +// Rango de fechas válido
No lo has resuelto todavía.

2024-11-28 09:31 UTC, JJ commented on internal/gestor_calidad_aire.go
> +	id                string
Si es por provincias, pon el nombre de la provincia o el área en el que esté.

2024-11-28 12:17 UTC, lmchaves commented on internal/datos_muestreo.go
> +// Rango de fechas válido
Se ha resuelto aqui: [d855e06](https://github.com/pablotl0/EnviroTrack/pull/10/commits/d855e064b095efa1f17622c2a4a90d7e1628fe1d)

2024-11-28 12:17 UTC, lmchaves commented on internal/gestor_calidad_aire.go
> +	id                string
Se ha modificado aqui:[d855e06](https://github.com/pablotl0/EnviroTrack/pull/10/commits/d855e064b095efa1f17622c2a4a90d7e1628fe1d)

2024-11-28 12:17 UTC, lmchaves commented
@pablotl0 ya esta listo para revisión

2024-11-28 16:01 UTC, pablotl0 approved these changes
@lmchaves Una vez cambiado eso, no veo ningún inconveniente mas y para esta aprobado

2024-11-28 16:01 UTC, pablotl0 commented on internal/calidad_aire.go
> +    Ubicacion     Ubicacion
Para que el modelo sea mas consistente la se debería validar que provincia del gestor de calidad sea igual que la provincia de la ubicación de la muestra.

2024-11-28 16:27 UTC, lmchaves commented on internal/calidad_aire.go
> +    Ubicacion     Ubicacion
Aqui esta arreglado: [9fe625d](https://github.com/pablotl0/EnviroTrack/pull/10/commits/9fe625da2cff383f09db8bfa112b597144051726)

2024-11-28 16:27 UTC, lmchaves commented
@JJ ya esta listo para revisión

2024-11-29 10:10 UTC, lmchaves commented on internal/contaminante.go
> +	Unidad        string
Está aquí corregido [caad847](https://github.com/pablotl0/EnviroTrack/pull/10/commits/caad8472d43d93dbedda35fdad6e43b64336f386)

2024-11-29 10:16 UTC, lmchaves commented on internal/calidad_aire.go
> +    Ubicacion     Ubicacion
Aquí esta modificado: [c2f784e](https://github.com/pablotl0/EnviroTrack/pull/10/commits/c2f784e479059fc5e98393664c23e726bdae8196)

2024-11-29 10:17 UTC, lmchaves commented
@pablotl0  ya está listo para revisión.

2024-11-29 11:37 UTC, pablotl0 approved these changes
@lmchaves Una vez cambiada la entidad, apruebo los cambios.

2024-11-29 11:37 UTC, pablotl0 commented on iv.yaml
> +entidad: internal/calidad_aire.go
Falta modificar la entidad

2024-11-29 11:46 UTC, lmchaves commented on iv.yaml
> +entidad: internal/calidad_aire.go
Aqui esta arreglado [24bb60a](https://github.com/pablotl0/EnviroTrack/pull/10/commits/24bb60ae943dab615700aede3270352e75af5230)

2024-11-29 11:47 UTC, lmchaves commented
Ya está listo para revisión @JJ

2024-11-29 12:33 UTC, JJ reviewed
Aparte de la entidad, tienes que buscar una única fuente de verdad para los datos; en este caso de Ubicación. Si vas hciendo el "camino" para trabajar con esto y no sabes donde están los datos, es que tienes que crear una entidad que los maneje y los contenga (y que sirva sobre única fuente de verdad)

2024-11-29 12:33 UTC, JJ commented on internal/calidad_aire.go
> +    DatosMuestreo map[time.Time]MuestraCalidadAire
time.Time es tiempo absoluto desde el 1 de enero del año 0. Es posible que no sea esto lo que busques.

2024-11-29 12:33 UTC, JJ commented on internal/ubicacion.go
> +type Ubicacion struct {
Si este es el objeto valor, tienes que tener una única fuente de verdad para este objeto valor.

2024-11-29 12:33 UTC, JJ commented on internal/gestor_calidad_aire.go
> +	datosCalidadAire  map[string][]DatosCalidadAire
Si este estring es la ubicación, deberías documentarlo llamando al atributo de una forma determinada, por ejemplo `datosCalidadAireParaSitio`

2024-11-29 13:00 UTC, pablotl0 commented on internal/ubicacion.go
> +	if provincia {
Has borrado la comprobación de que este vacio

2024-11-29 13:08 UTC, lmchaves commented on internal/ubicacion.go
> +	if provincia {
Ya esta solucionado [178e517](https://github.com/pablotl0/EnviroTrack/pull/10/commits/178e5170f11b29eb2e3d3299ee0a0c58af722c7f)

2024-11-29 13:17 UTC, lmchaves commented on internal/calidad_aire.go
> +    DatosMuestreo map[time.Time]MuestraCalidadAire
esta resuelto aqui: [ee1c510](https://github.com/pablotl0/EnviroTrack/pull/10/commits/ee1c51002e1b9598e8190dc7e88ee5d03778fce9)

2024-11-29 13:19 UTC, lmchaves commented
@pablotl0 ya esta listo para revisión

2024-11-29 13:27 UTC, pablotl0 approved these changes

2024-11-29 13:30 UTC, lmchaves commented
@JJ ya está listo para revisión

2024-12-02 07:13 UTC, JJ requested changes
Hay comentarios sin resolver y otros en los que no se ha entendido sobre qué se hacía el comentario. También rogaría a @pablotl0 que hiciera estas mínimas comprobaciones en vez de aprobar. Al fin y al cabo, quien va a tener que usar este código es él.

2024-12-02 07:13 UTC, JJ commented on internal/calidad_aire.go
> +type DatosCalidadAire struct {
¿Que el fichero se llame `calidad_aire` y esto `DatosCalidadAire` sigue las mejores prácticas de Go?

2024-12-02 07:13 UTC, JJ commented on internal/calidad_aire.go
> +    DatosMuestreo map[string]MuestraCalidadAire //YYYY-MM-DD
¿Los comentarios al final del código siguen las mejores prácticas? ¿Que uses un map para algo que son 3 cantidades, año, mes y día lo sigue? Si quieres todos los datos de un año, ¿cómo lo haces?

2024-12-02 10:49 UTC, lmchaves commented
@pablotl0 ya esta listo para revisión

2024-12-02 12:07 UTC, pablotl0 requested changes
@lmchaves

2024-12-02 12:27 UTC, lmchaves commented on internal/datos_muestreo.go
> +	FechaInicial  time.Time
Aqui esta cambiado: [c8a6a25](https://github.com/pablotl0/EnviroTrack/pull/10/commits/c8a6a259b21fc1726bf1260a21a682a6789c36d0)

2024-12-02 12:27 UTC, lmchaves commented on internal/gestor_ubicaciones.go
> +		if _, exists := mapUbicaciones[u.Provincia]; exists {
Aqui esta cambiado: [6a08e30](https://github.com/pablotl0/EnviroTrack/pull/10/commits/6a08e3009d4d0e5716b94b73bb402e664cf543b6)

2024-12-02 12:27 UTC, lmchaves reviewed
Ya esta listo apra revisón @pablotl0

2024-12-02 12:40 UTC, pablotl0 commented on internal/datos_muestreo.go
> +type Fecha struct {
Crea un archivo aparte para que cada clase tenga una única funcion

2024-12-02 13:13 UTC, pablotl0 requested changes
@lmchaves

2024-12-02 13:13 UTC, pablotl0 commented on internal/ubicacion.go
> +	return &Ubicacion{Provincia: provincia,Municipio: municipio  Latitud: latitud, Longitud: longitud}, nil
Hay un error en municipio.

2024-12-02 14:43 UTC, lmchaves commented on internal/datos_muestreo.go
> +type Fecha struct {
Esta aqui arreglado: [f04d307](https://github.com/pablotl0/EnviroTrack/pull/10/commits/f04d30718c6157ae0b9397a8c1eba9a1e01017fb)

2024-12-02 16:03 UTC, pablotl0 requested changes
@lmchaves

2024-12-02 16:03 UTC, pablotl0 commented on internal/datos_muestreo.go
> +type MuestraCalidadAire struct {
Para buenas prácticas el archivo debe tener el mismo nombre que la estructura

2024-12-02 16:03 UTC, pablotl0 commented on internal/calidad_aire.go
> +type MuestreoCalidadAire struct {
Para buenas prácticas el nombre del struct y del archivo debe ser igual y debería diferenciarse de muestra de calidad del aire

2024-12-03 14:12 UTC, lmchaves commented on internal/calidad_aire.go
> +type MuestreoCalidadAire struct {
Cambio el nombre para que no sea como en datos_muestreo [625c79f](https://github.com/pablotl0/EnviroTrack/pull/10/commits/625c79fec98c1c3d7ae5b2ac23bd3826e12de712)

2024-12-03 14:41 UTC, pablotl0 approved these changes
@lmchaves Ya esta aprobado

2024-12-03 14:47 UTC, lmchaves commented
@JJ ya está listo para revisión

2024-12-03 16:35 UTC, JJ requested changes
Aunque esto sea para superar el objetivo de @lmchaves , también se trata de que hagáis vuestro trabajo porque al final vais a tener que usarlo. Has hecho un esfuerzo importante tratando de crear las entidades necesarias, pero una modelización correcta debe buscar el mínimo esfuerzo por parte de la persona que lo use. Y sobre todo seguir las buenas prácticas.

2024-12-03 16:35 UTC, JJ commented on internal/calidad_aire.go
¿Qué dicen las mejores prácticas de Go sobre el nombre del fichero?
Cuando os haga un comentario, por favor miradlo en todo el documento.
@pablotl0 esto es algo muy básico. ¿Te parece que la mejor forma de que yo emplee el tiempo es comprobar estas cosas?

2024-12-03 16:35 UTC, JJ commented on internal/calidad_aire.go
> +type CalidadAireUbicacion struct {
Si a primera vista no se entiende el nombre de una variable o tipo, es que el nombre no modela correctamente el dominio. @pablotl0 esto también es algo muy básico. Llamad a las cosas por su nombre. Si no hay limitación en el tamaño de los identificadores, ¿para qué lo reducís hasta hacerlo incomprensible?

2024-12-03 16:35 UTC, JJ commented on internal/calidad_aire.go
> +	Provincia     string
Los comentarios deben resolverse correctamente sea o no el profesor quien los ponga. Si hay varios revisores, no puedes tampoco marcarla tú @pablotl0 como resuelta, porque yo la voy a tener que mirar de todas formas.

2024-12-03 16:35 UTC, JJ commented on internal/datos_muestreo.go
> +	FechaInicial  Fecha
Esta fecha, ¿qué tiene que ver con la que hay en `CalidadAireUbicacion`

2024-12-03 16:35 UTC, JJ commented on internal/fecha.go
> +type Fecha struct {
¿De veras que Go no es capaz de manejar esto?

2024-12-03 16:35 UTC, JJ commented on internal/fecha.go
> +	Mes int
Y si puede, ¿de veras que no hay un tipo más preciso que Int?

2024-12-03 16:35 UTC, JJ commented on internal/gestor_ubicaciones.go
> +	ubicaciones map[string][]Ubicacion
Si esto es un array, ¿para qué quieres darle una clase para él solo? ¿Cómo tendrías que acceder desde el otro "Gestor"?

2024-12-04 18:24 UTC, lmchaves commented on internal/calidad_aire.go
> +type CalidadAireUbicacion struct {
se cambia aqui: [14b8fad](https://github.com/pablotl0/EnviroTrack/pull/10/commits/14b8fad616bc3e6bf397b181de142367d8936c27)

2024-12-04 18:24 UTC, lmchaves commented on internal/fecha.go
> +	Mes int
se cambia aqui: [14b8fad](https://github.com/pablotl0/EnviroTrack/pull/10/commits/14b8fad616bc3e6bf397b181de142367d8936c27)

2024-12-04 18:31 UTC, lmchaves commented on internal/datos_muestreo.go
> +	FechaInicial  Fecha
La razón por la cual utilizo un map[Fecha]MuestraCalidadAire en DatosMuestreo es para facilitar el acceso eficiente a los datos de calidad del aire basados en una fecha específica. Cada MuestraCalidadAire tiene una FechaInicial que representa la fecha de la medición, y al usar la estructura Fecha como clave en el mapa, se puede acceder a las muestras de forma más directa y rápida usando la fecha correspondiente (año, mes, día).

2024-12-04 18:35 UTC, JJ commented on internal/datos_muestreo.go
> +	FechaInicial  Fecha
No te estoy preguntando eso. Una vez más, tienes que entender el concepto de "Única fuente de verdad"

2024-12-05 08:06 UTC, lmchaves commented on internal/datos_muestreo.go
> +	FechaInicial  Fecha
Aquí lo he modificado:
[7d2ad70](https://github.com/pablotl0/EnviroTrack/pull/10/commits/7d2ad70f570b0f60558f929d38062bee51fe16ee)

2024-12-05 08:34 UTC, JJ requested changes
Por favor, @pablotl0 , revísalo cuando haya terminado.

2024-12-05 08:34 UTC, JJ commented on internal/fecha.go
> +    Año int
¿El año -3 es válido?

2024-12-05 08:34 UTC, JJ commented on internal/fecha.go
> +    Día int
¿el día -3 es válido?

2024-12-05 08:34 UTC, JJ commented on internal/fecha.go
> +    if mes < 1 || mes > 12 {
¿Esto funciona?

2024-12-05 08:51 UTC, lmchaves commented on internal/fecha.go
> +    Año int
Aquí ha sido arreglado: [301dc75](https://github.com/pablotl0/EnviroTrack/pull/10/commits/301dc754c4f462c2b313fa70a911a4b4014fa90b)

2024-12-05 08:51 UTC, lmchaves commented on internal/fecha.go
> +    Día int
Aquí ha sido arreglado: [301dc75](https://github.com/pablotl0/EnviroTrack/pull/10/commits/301dc754c4f462c2b313fa70a911a4b4014fa90b)

2024-12-05 08:51 UTC, lmchaves commented on internal/fecha.go
> +    if mes < 1 || mes > 12 {
Aquí ha sido arreglado: [301dc75](https://github.com/pablotl0/EnviroTrack/pull/10/commits/301dc754c4f462c2b313fa70a911a4b4014fa90b)

2024-12-05 08:51 UTC, lmchaves commented on internal/fecha.go
> +type Fecha struct {
Aquí ha sido arreglado: [301dc75](https://github.com/pablotl0/EnviroTrack/pull/10/commits/301dc754c4f462c2b313fa70a911a4b4014fa90b)

2024-12-05 08:52 UTC, lmchaves commented
@pablotl0 ya está lsito para revisión

2024-12-05 09:22 UTC, lmchaves commented
@JJ ya está listo para revisión

2024-12-05 10:31 UTC, JJ commented
Por favor, @pablotl0 , revísalo tú antes.

2024-12-05 11:36 UTC, pablotl0 approved these changes
@lmchaves  arregla el nombre del archivo calidad_aire.go

2024-12-05 12:17 UTC, lmchaves commented
Ya esa listo @JJ

2024-12-06 10:00 UTC, JJ requested changes
Sigue habiendo comentarios sin resolver.

2024-12-09 08:30 UTC, lmchaves commented on internal/calidad_aire.go
Aqui esta resuelto [473cd93](https://github.com/pablotl0/EnviroTrack/pull/10/commits/473cd9343b65b2a798b7fac4f7fb0114dc47b0ec)

2024-12-09 08:30 UTC, lmchaves commented
@JJ ya está lsito para revisión

2024-12-10 16:25 UTC, JJ approved these changes
:+1: 
Por parte de @lmchaves está todo hecho. Si quiere @pablotl0 admitir código que no sigue las mejores prácticas, allá él.

2024-12-10 16:25 UTC, JJ commented on internal/datos_muestreo.go
> +type MuestraCalidadAire struct {
¿`datos_muestreo` es el misno nombre que `MuestraCalidadAire`? @pablotl0 ¿por qué lo marcas como resuelto si no está cambiado?

2024-12-11 20:07 UTC, merged