[IV-24-25] Objetivo 1
pablotl0/EnviroTrack pull request #5
Opened 2024-10-10 09:11 UTC by pablotl0

* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2024-10-10 12:41 UTC, MarioRgzLpz commented
Buenas se me ha asignado revisar esta PR. Tras mirarla te voy a señalar los fallos que he encontrado.

2024-10-10 12:43 UTC, MarioRgzLpz commented on .gitignore
El .gitignore no debe aparecer en esta PR. Añadelo a tu main y haz un rebase en la rama desde la que has lanzado la PR para que no aparezcan estos cambios.

2024-10-10 12:49 UTC, MarioRgzLpz commented on docs/ob0/README.md
No es necesario tener dos Readme pero puesto que lo que tienes aqui es para mostrar la configuración (algo del objetivo 0) no deben aparecer los cambios en este PR al igual que el .gitignore.

2024-10-10 12:53 UTC, MarioRgzLpz commented on docs/ob0/config.png
De igual forma esto no va aquí.

2024-10-10 12:53 UTC, MarioRgzLpz commented on docs/ob0/github-key.png
Ni esto.

2024-10-10 12:53 UTC, MarioRgzLpz commented on docs/ob0/perfil.png
Ni esto.

2024-10-10 12:53 UTC, MarioRgzLpz commented on docs/ob0/public-key.png
Ni esto.

2024-10-10 12:56 UTC, MarioRgzLpz commented on docs/User-stories.md
> +### [HU0] Blanca: Desarolladora
```suggestion
### [HU0] Blanca: Desarrolladora
```
Typo

2024-10-10 13:02 UTC, MarioRgzLpz commented on docs/User-stories.md
> +- Se identifican todas las entidades y relaciones necesarias para el diseño del sistema.
Las HUs muestran deseos de una persona y resuelven un problema, sin embargo, esta HU no resuelve ningún problema porque estas hablando en general del problema (¿cuál?). Además las HUs deben comenzar por la 1 como aparece en el guión https://jj.github.io/IV/documentos/proyecto/1.Planificacion.

2024-10-10 13:10 UTC, MarioRgzLpz commented on docs/User-journeys.md
En los user jorneys debes explicar el uso que se le daría a **tu** aplicación, no lo que debe hacer cada usuario  sin nuestra aplicación para obtener lo que quiere. Piensa que el user-jorney es para explicar el posible uso y así aclarar dudas en su creación.

2024-10-10 13:25 UTC, MarioRgzLpz commented on docs/User-stories.md
Recomiendo que dejes en claro el radio de acción mediante las historias. ¿Va a ser solo en Granada o no hay limite? ¿Cuál es el formato de los datos y que datos se extraen? Has hablado de nivel de polución o calidad del aire, pero ¿son solo esos los que va a necesitar alguien como Juan José? Recuerda que especificar todo lo necesario es importante para que cualquier persona encargada de desarrollar el proyecto pudiera hacerlo de forma autónoma.

2024-10-11 08:14 UTC, Mario25402 commented
Hola, aparte de los cambios sugeridos de mi tocayo como puede ser lo de limitar los documentos necesarios a este PR excluyendo archivos de configuración y fotos del objetivo 0, respecto a los milestones, cuesta diferenciar que se considera el objetivo y que se considera entregable ya que estas mezclando ambas cosas y cuesta un poco ver los conceptos.

2024-10-11 16:35 UTC, pablotl0 commented on docs/User-stories.md
> +- Se identifican todas las entidades y relaciones necesarias para el diseño del sistema.
He quitado esa HU ya que no tenia sentido y no mostraba el deseo de una persona sino del desarollador de la aplicación. Lo cuál no tenía nada que ver

2024-10-11 16:36 UTC, pablotl0 commented on docs/User-journeys.md
Ya he modificado cuales serían las acciones que harían los distintos usuarios en mi aplicación

2024-10-11 16:38 UTC, pablotl0 commented on docs/User-stories.md
He profundizado mas en las historias de usuario (indicando el radio acción y los datos que se van a usar) para especificar cuales son los problemas y deseos de los distintos usuarios

2024-10-12 11:33 UTC, MarioRgzLpz commented
@pablotl0 Muchas gracias por los cambios. Te recomiendo, para facilitar a los revisores, incluir cada cambio solicitado en un commit y tras esto referenciarlo donde se te haya pedido. También que una vez realizados esos cambios y aceptados por el revisor resuelvas las conversaciones donde se solicitaban. 

Además parece que no has hecho los cambios correctamente, ya que siguen apareciendo los archivos aunque ahora eliminados. Puedes evitar eso cambiando en tu rama main directamente y luego haciendo un `git rebase`. Si tienes dudas de como hacerlo, pregunta al profesor, a mi o a nuestro gran amigo ChatGPT.

2024-10-13 09:31 UTC, pablotl0 commented
> Hola, aparte de los cambios sugeridos de mi tocayo como puede ser lo de limitar los documentos necesarios a este PR excluyendo archivos de configuración y fotos del objetivo 0, respecto a los milestones, cuesta diferenciar que se considera el objetivo y que se considera entregable ya que estas mezclando ambas cosas y cuesta un poco ver los conceptos.

Hola, he hecho los cambios en los milestones especificando mas el producto minimo viable, ya que no era. ¿He aclarado mejor el concepto?

2024-10-13 14:37 UTC, MarioRgzLpz commented
@pablotl0 Ahora si que veo todo bastante completo aunque hecho un poco en falta algo más de contexto sobre el formato que tendrán los datos como puede ser un ejemplo en el readme mediante una URL o en otro fichero que complemente lo ya descrito en las HUs, más que nada para evitar que cuando alguien comience a trabajar con tu repositorio te pregunte sobre esto. Aclarando eso, por mi parte tienes el aprobado. A seguir currando!

2024-10-13 14:38 UTC, MarioRgzLpz approved these changes

2024-10-15 09:04 UTC, Mario25402 approved these changes
Por mi parte lo veo correcto, buen trabajo!

2024-10-17 06:45 UTC, pablotl0 commented
@JJ revisión

2024-10-17 07:11 UTC, JJ reviewed
Por favor, mirad el fichero de errores comunes.
También el formato de los datos es menos útil que los datos en si.

2024-10-17 07:11 UTC, JJ commented on docs/Milestones.md
> +- **Diagrama técnico detallado** que especifique las fuentes de datos y su integración en la plataforma.
Por favor, no pidáis cosas aleatorias que no son útiles para el proceso de desarrollo.

2024-10-17 11:00 UTC, pablotl0 commented
@JJ revision

2024-10-17 11:09 UTC, JJ reviewed
Por favor, repasa los errores frecuentes. Por cada uno que identifiques, haz un commit separado indicando lo que has corregido y como.

2024-10-17 11:09 UTC, JJ commented on docs/Milestones.md
> +- Código con las entidades del problema (estaciones meteorológicas, calidad del aire, factores ambientales), las características de cada entidad, como la temperatura o precipitaciones para los factor
¿Estas entidades del problema las sabes ya antes de que se haga el modelo del problema? Por favor, mira [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md)

> El exceso de detalles hace que se fuerce a soluciones determinadas, y hace que haya que cambiar una cantidad excesiva de cosas.

2024-10-21 14:32 UTC, pablotl0 commented on docs/Milestones.md
> +- Código con las entidades del problema (estaciones meteorológicas, calidad del aire, factores ambientales), las características de cada entidad, como la temperatura o precipitaciones para los factor
En el commit 0788190e lo he corregido.
He generalizado el producto ya que este era demasiado específico y se adentra en el trabajo que debe hacer el desarollador mas adelante.

2024-10-24 06:36 UTC, pablotl0 commented
@JJ revision

2024-10-24 10:09 UTC, JJ requested changes
Por favor, [lee los errores frecuentes del objetivo 1](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md). Os rogaría que cuando solicitéis revisión no os limitéis a corregir estrictamente los comentarios que se hayan hecho, sino que miréis si puede haber algo aplicable al resto del PR, que esté en el mismo comentario o en los errores frecuentes.

2024-10-24 10:09 UTC, JJ commented on docs/Milestones.md
> +#### [M0] Milestone 0: **Diseño del modelo conceptual y viabilidad técnica**
¿"Viabilidad técnica" es un producto?

2024-10-24 10:09 UTC, JJ commented on docs/Milestones.md
> +- Código que implemente el modelo conceptual con las entidades del problema y las relaciones entre estas entidades.
¿Qué problema?

2024-10-24 14:26 UTC, pablotl0 commented on docs/Milestones.md
> +- Código que implemente el modelo conceptual con las entidades del problema y las relaciones entre estas entidades.
En el commit a0a841eb lo he corregido. 
Especificando que el problema esta relacionado con el tratamiento de datos ambientales, mencionado en el HU01

2024-10-25 15:10 UTC, pablotl0 commented
@JJ revision

2024-10-28 06:27 UTC, JJ requested changes
Convendría que repasaras [el guión](http://jj.github.io/IV/documentos/proyecto/2.Modelo) para entender un poco mejor los conceptos de *milestone* e *historia de usuario*. Lo esencial, en todo caso, es que entendáis esto como un documento de trabajo, no una combinación de palabras que te hace aprobar o no una práctica. Lo que escribáis aquí es lo que vais a usar como guía en el resto de la asignatura, vosotros mismos o la persona que trabaje en eu proyecto.

2024-10-28 06:27 UTC, JJ commented on docs/Milestones.md
> +- Código que implemente el modelo conceptual con las entidades del problema, asociado a las necesidades de la HU001 con la gestión de los datos ambientales, y las relaciones entre estas entidades.
¿Qué es el "modelo conceptual del problema"? Si te entregan un "código", ¿qué vas a hacer para cerciorarte de que es el modelo conceptual?
Por otro lado, ¿decir "con la gestión de los datos ambientales" crees que aclara de alguna forma lo que contiene la HU001? Si los datos ambientales están en esa HU, ¿por qué lo añades? Y si  no lo están, ¿crees que añadir algo aquí aporta algo a la comprensión del problema?

2024-10-28 06:27 UTC, JJ commented on docs/Milestones.md
> +#### [M1] Milestone 1: **Módulo de Consolidación de Datos y Visualización Básica**
¿Consolidación de datos? ¿Qué es la consolidación de datos? ¿Visualización básica? ¿Crees que inmediato a un "modelo conceptual" ya estás listo para hacer una "visualización"? ¿No habrá algún paso intermedio?

2024-10-28 06:27 UTC, JJ commented on docs/Milestones.md
> +- Incluye las entidades del dominio y sus relaciones en el código, asociadas a la información de la HU001.
Las "entidades del dominio y sus relaciones" ¿son aparte del "modelo conceptual"? Si te entrega el código una persona, ¿cómo vas a comprobar que esas "entidades de dominio y sus relaciones" están incluidas?

2024-10-28 06:27 UTC, JJ commented on docs/User-stories.md
> +Como investigador ambiental, quiero acceder a una única plataforma que me permita consultar, ver y descargar datos fiables de varias fuentes en tiempo real, para agilizar mi proceso de análisis.
¿"ver" es un problema o una solución a un problema? ¿Has puesto esto porque has añadido "visualización" al milestone **1**? ¿Crees que en 2 milestones, uno de ellos interno y con el número 0, se puede resolver el problema de un usuario?

2024-10-28 18:08 UTC, pablotl0 commented on docs/Milestones.md
> +- Código que implemente el modelo conceptual con las entidades del problema, asociado a las necesidades de la HU001 con la gestión de los datos ambientales, y las relaciones entre estas entidades.
Lo he arreglado en el commit 90ea954b.
Ya que el termino modelo conceptual no aportaba valor al desarollador y podia causarle confusión.
Respecto a los datos ambientales los he borrado ya que si aparecen en la HU.

2024-10-28 18:15 UTC, pablotl0 commented on docs/Milestones.md
> +- Incluye las entidades del dominio y sus relaciones en el código, asociadas a la información de la HU001.
Lo he arreglado el commit 49f1fe3d.
He especificado mas la viabilidad haciendo referencia a la medición de datos ambientales, con el objetivo de aclarar el propósito del producto.

2024-10-28 18:26 UTC, pablotl0 commented on docs/Milestones.md
> +#### [M1] Milestone 1: **Módulo de Consolidación de Datos y Visualización Básica**
Lo he arreglado en el commit c65ad540.
He especificado mas el concepto de consolidación de datos ya que era una explicación vaga y no aportaba claridad.
He reducido el M1 a la recolección y organización de los datos, ya que el M1 anterior no era un producto mínimo al abarcar otro PMV como podría ser la visualización.

2024-10-28 18:32 UTC, pablotl0 commented on docs/User-stories.md
> +Como investigador ambiental, quiero acceder a una única plataforma que me permita consultar, ver y descargar datos fiables de varias fuentes en tiempo real, para agilizar mi proceso de análisis.
Pienso que es parte del problema del investigador puedan ver los datos, esto no significa que deba haber una interfaz compleja sino simplemente tener acceso a los datos para verlos en pantalla.  
No era necesario ponerlo ya que se puede entender que necesitara ver los datos, pero lo escribí para aclararlo.

2024-10-28 18:32 UTC, pablotl0 commented
@JJ revision

2024-10-29 13:53 UTC, JJ commented on docs/User-stories.md
> +Como investigador ambiental, quiero acceder a una única plataforma que me permita consultar, ver y descargar datos fiables de varias fuentes en tiempo real, para agilizar mi proceso de análisis.
No estás contestando a mi pregunta. ¿Es un problema o una solución?

2024-10-29 13:54 UTC, JJ requested changes
Por favor, resolved *todos* los comentarios.

2024-10-30 08:25 UTC, JJ commented on docs/User-stories.md
> +Como investigador ambiental, quiero acceder a una única plataforma que me permita consultar, ver y descargar datos fiables de varias fuentes en tiempo real, para agilizar mi proceso de análisis.
Quizás deberías revisar tu concepto mental de qué es un problema y qué no. Entender qué constituye un problema es fundamental para poder expresarlo en las historias de usuario, y más adelante cuando se creen los issues en el objetivo 2.

2024-10-30 11:01 UTC, pablotl0 commented on docs/User-stories.md
> +Como investigador ambiental, quiero acceder a una única plataforma que me permita consultar, ver y descargar datos fiables de varias fuentes en tiempo real, para agilizar mi proceso de análisis.
@JJ  ya lo he corregido en el commit f551dd7.
Eliminándolo al no ser una necesidad específica del usuario

2024-11-05 10:43 UTC, pablotl0 commented
@JJ revision

2024-11-05 13:36 UTC, JJ requested changes
Sería conveniente que trataras de entender qué es un milestone, y qué es un "modelo del problema". Que uses combinaciones diferentes de palabras para decir algo que no entiendes no te va a acercar a comprenderlo.
Lee también en errores frecuentes lo que dice sobre milestones más allá del 1.

2024-11-05 13:36 UTC, JJ commented on docs/Milestones.md
> +- Código que implementa las entidades relacionadas con el problema y sus relaciones, alineado con los necesidades de la HU001.
¿Qué son las "entidades relacionadas con el problema *y sus relaciones*"? ¿Son el "diseño del modelo del problema"? ¿Cómo se "alinea" una "entidad y sus relaciones" con una HU?

2024-11-07 16:15 UTC, JJ requested changes
De veras que sería conveniente que entendiérais lo que estáis pidiendo y por qué.

2024-11-07 16:15 UTC, JJ commented on docs/Milestones.md
> +Establecer el dominio del problema descrito en la [HU001](https://github.com/pablotl0/EnviroTrack/issues/2) con el fin de estructurar y centralizar la información demográfica actualmente distribuida
Si la "información demográfica" está en la HU001, ¿por qué la mencionas? Si no está, ¿cómo va a saber esa persona qué tiene que hacer?

Por otro lado, "establecer el dominio" ¿qué tiene que ver con el "modelo del problema"? No sé tampoco qué quiere decir "establecer el dominio"

2024-11-07 16:15 UTC, JJ commented on docs/Milestones.md
> +Se deberán definir los recursos necesarios para abordar el problema, incluyendo el método para extraer los datos de las fuentes especificadas en la [HU001](https://github.com/pablotl/EnviroTrack/issu
"Definir" los "recursos" ¿es parte del modelo? ¿Es otra cosa? ¿Por qué hay que hacerlo ahora?

2024-11-08 13:16 UTC, JJ reviewed
Venga, ya queda muy poco

2024-11-08 13:16 UTC, JJ commented on docs/Milestones.md
> +- El código que represente la lógica de negocio del problema descrito en la [HU001] (https://github.com/pablotl0/EnviroTrack/issues/2) .
Pon las cosas medianamente bien. Tal como lo has formulado, no es un criterio, y además no dices como vas a comprobar esa viabilidad.

2024-11-08 13:25 UTC, JJ reviewed
👍

2024-11-08 13:27 UTC, merged